apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app-container
          image: webapp:latest 
          ports:
            - containerPort: 5000 
          resources:
            limits:
              cpu: "0.5"  
              memory: "512Mi" 
            requests:
              cpu: "0.1"  
              memory: "256Mi" 
